[phases.setup]
nixPkgs = ["php", "nodejs"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build",
  "touch /tmp/database.sqlite",
  "php artisan migrate --force",
  "php artisan db:seed --force"
]

