[phases.setup]
nixPkgs = ["nodejs"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build",
  "touch /tmp/database.sqlite",
  "php artisan migrate --force",
  "php artisan db:seed --force"
]
[variables]
NIXPACKS_PHP_ROOT_DIR = "public"
